### ISSUE TITLE
Enhancment: XPEnchanter - additional Functions

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#39]
As I see you try to replace the Advanced Enchanting Table from Enchanting Plus with your XPEnchanter.
In that case it might be good to add some additional features:
- Make the existing Enchantments of an item visible in the XPEnchanter
- Allow also removing the existing Enchantments.
- Show the mod from which an Enchantment comes or at least its Enchantment ID.
- Sometimes there are Enchantments available from different mods which have the same name - like Swiftness for example. Allow selecting one of them, selectable by the user, which one.
- A scrolling function with the mouse wheel would also be nice.

That way your XPEnchanter might be really able to replace the Advanced Enchanting Table.

**Comment by DrZed** [comment]
You're wrong... I'm not replacing it, it's just an easier way of implementing my own enchanting table rather than creating my own enchanting system (waiting for v3 for that) I decided to just create this reading from the enchants array...
As for the advanced enchanting table I saw the source if anything I could just clean up and update it with my own mod enchants capable...

**Comment by DrZed** [comment]
Things I will do, 
Make existing Enchantments visible
Allow removing existing Enchantments.
Show the mod (on mouse over)
scrolling with the mouse wheel (if I find a way to do so without actually making a scroll bar)
As well as sorting by mod, by alphabet, and by numberical id

**Comment by walkerjonny** [comment]
Sounds good so far. That way the XPEnchanter should be a really useful Enchantment Table.

About the Advanced Enchantig Tabe - if I understand you correctly you would have preferred to update it rather then creating an own Enchanting Table, right?
As I have just seen, Enchanting Plus is maintained now by Darkhax and his team and they are working actually on a new version. See:
http://minecraft.curseforge.com/projects/enchanting-plus
https://github.com/Epoxide-MC/Enchanting-Plus
Maybe you want to talk to them to get your issues fixed in the new version.

**Comment by DrZed** [comment]
Yeah I already knew about it

**Comment by bloodyraoul** [comment]
I use the 1.7.10 version and i think the XPEnchanter is really too powerfull.
Enchantments sould cost more, or not only XP
Is there a way to change the cost of enchantments coming form other mods ?
Because "Soulbound" from Ars Magica 2 is only 15 Levels ;)
Maybe also add a parameter to disable the crafting of XpEnchanter

**Comment by DrZed** [comment]
Sir soulbound default only costs 8 levels, look at enchanting plus. I have mine with a slightly higher cost than normal.
I have the costs of all enchants enhanced in my table.

**Comment by DrZed** [comment]
Also I believe I have a cost multiplier config... And I plan to have souls count toward charge instead of xp...
