### ISSUE TITLE
Enchantments draining lots of both charges and levels

### ISSUE THREAD

**Issue by walkerjonny** [HxCKDMS/HxCEnchants#50]
I'm playing with HxCEnchants v2.3.4 and HxCCore v1.12.4.
I have discovered a lot of draining of both charges and XP levels.
The charges are draining every second even if there is no enchantment that is actively used.
The levels are also being drained but not every second. That seems to happen every 30 to 60 seconds or so. But then more levels at once (somewhat between 10 to 30 every time) are stripped.
That prize is way too high for the enchantments.
I would suggest to handle enchantment in the following way:
There should be a short counter (30 to 60 seconds) and a long counter (90 to 180 seconds).
Enchantments that are not always actively used should drain the defined amount of charge every time the short counter is counted down. The short counter starts to count down at the beginning of using that enchantment and cannot be stopped until it has counted down.  
Enchantments that are always actively used should drain the defined amount of charge every time the long counter is counted down.
Level draining should not occur until an enchanted item has no charges left and only if there is a config option within the config file that is activated to allow that to happen.
Also Enchantments that can be added to more than one item should either be cumulated (example: Repair level 5 on all armor parts = up to 20 damage points that can be repaired within the given time) or they should reduce the required charge with the following formula while the effect stays the same: defined amount of Charge / amount of items with the specific Enchantment.
What do you think about this?

Oh, and FYI:
I for myself prefer to use the blocks for both adding enchantments and adding charge. They may have some little issues but nothing that urges me to get rid of them. For me it is easier and more convenient to use them.

**Comment by DrZed** [comment]
I have no idea what would be causing the xp drainage other than the shifting, I have no code that subtracts from xp, excluding the charger and shift function

**Comment by DrZed** [comment]
BTW I already have a delayed drainage for most the enchants, it's a configurable update timer default updates 5x slower than redstone I think.

**Comment by DrZed** [comment]
Auras, armor enchants, repair and regen are on the delayed player tick I made. feather fall, meteor fall, swiftness, vitality, and fly, aren't on delayed tick.

**Comment by DrZed** [comment]
Okay your post was long, I never read the whole thing....
Repair is per breakable item, and they ALL tick at 1 time, but repair repairs only the item it is on. so lvl 5 repairs 5 durability and it's on the delayed tick.
Vitality only counts on the chestplate.
Regen does stack for all armor, so lvl 5 on each armor should in theory regen 5-10 hearts every 10 seconds. I don't remember the math I have behind that. thinking of making it a formula.
Charge is charged to an item when it is held in hand and the keybind is pressed (now).
The charge required for every enchant is based on when it is triggered and is configurable, thus aura enchants, flight, swift, vitality, are all draining constantly. (well aura only when entities other than player is in range, or blocks for some).
I believe your xp drain was due to holding shift and not realising it. because in that version xp drained is by shifting with held item is enchanted (tinker tools are almost always "enchanted" by game code).
